<?php

namespace App\Http\Controllers;

class PruebaController extends Controller
{
    public function index()
    {
        $casos = [
            [
                'id' => 'CP01',
                'historia' => 'HU01 - Registro y Validacion de Identidad',
                'modulo' => 'Registro',
                'caso' => 'Registro valido de estudiante',
                'tipo' => 'Unitaria / Caja negra',
                'categoria' => 'unitaria',
                'entrada' => 'DNI 74698202, Codigo 474698202, Gafete 444',
                'resultado' => 'Registro valido, rol estudiante',
                'estado' => 'PASSED',
            ],
            [
                'id' => 'CP02',
                'historia' => 'HU01 - Registro y Validacion de Identidad',
                'modulo' => 'Registro',
                'caso' => 'Registro valido de docente',
                'tipo' => 'Unitaria / Caja negra',
                'categoria' => 'unitaria',
                'entrada' => 'DNI 25863008, Codigo 725863008, Gafete 443',
                'resultado' => 'Registro valido, rol docente',
                'estado' => 'PASSED',
            ],
            [
                'id' => 'CP03',
                'historia' => 'HU01 - Registro y Validacion de Identidad',
                'modulo' => 'Registro',
                'caso' => 'DNI no coincide con codigo institucional',
                'tipo' => 'Unitaria / Caja negra',
                'categoria' => 'unitaria',
                'entrada' => 'DNI 11111111, Codigo 474698202, Gafete 444',
                'resultado' => 'Registro rechazado por DNI no coincidente',
                'estado' => 'PASSED',
            ],
            [
                'id' => 'CP04',
                'historia' => 'HU01 - Registro y Validacion de Identidad',
                'modulo' => 'Registro',
                'caso' => 'Prefijo de rol invalido',
                'tipo' => 'Unitaria / Caja negra',
                'categoria' => 'unitaria',
                'entrada' => 'DNI 74698202, Codigo 974698202, Gafete 444',
                'resultado' => 'Registro rechazado por rol institucional invalido',
                'estado' => 'PASSED',
            ],
            [
                'id' => 'CP05',
                'historia' => 'HU01 - Registro y Validacion de Identidad',
                'modulo' => 'Registro',
                'caso' => 'Gafete no corresponde al rol institucional',
                'tipo' => 'Unitaria / Tabla de decisiones',
                'categoria' => 'unitaria',
                'entrada' => 'DNI 74698202, Codigo 474698202, Gafete 443',
                'resultado' => 'Registro rechazado por gafete incompatible',
                'estado' => 'PASSED',
            ],
            [
                'id' => 'CP06',
                'historia' => 'HU02 - Gestion de Prestamos y Exclusividad',
                'modulo' => 'Prestamos',
                'caso' => 'Estudiante recibe prestamo por 7 dias',
                'tipo' => 'Unitaria / Regla de negocio',
                'categoria' => 'unitaria',
                'entrada' => 'Rol estudiante, fecha 2026-06-25',
                'resultado' => 'Devolucion 2026-07-02, 7 dias',
                'estado' => 'PASSED',
            ],
            [
                'id' => 'CP07',
                'historia' => 'HU02 - Gestion de Prestamos y Exclusividad',
                'modulo' => 'Prestamos',
                'caso' => 'Docente recibe prestamo por 14 dias',
                'tipo' => 'Unitaria / Regla de negocio',
                'categoria' => 'unitaria',
                'entrada' => 'Rol docente, fecha 2026-06-25',
                'resultado' => 'Devolucion 2026-07-09, 14 dias',
                'estado' => 'PASSED',
            ],
            [
                'id' => 'CP08',
                'historia' => 'HU02 - Gestion de Prestamos y Exclusividad',
                'modulo' => 'Prestamos',
                'caso' => 'Rol invalido no puede recibir prestamo',
                'tipo' => 'Unitaria / Caja negra',
                'categoria' => 'unitaria',
                'entrada' => 'Rol invitado, fecha 2026-06-25',
                'resultado' => 'Prestamo rechazado por rol invalido',
                'estado' => 'PASSED',
            ],
            [
                'id' => 'CP09',
                'historia' => 'HU02 - Gestion de Prestamos y Exclusividad',
                'modulo' => 'Prestamos',
                'caso' => 'Libro disponible puede ser prestado',
                'tipo' => 'Integracion / Caja gris',
                'categoria' => 'integracion',
                'entrada' => 'Usuario estudiante, libro DISPONIBLE, fecha 2026-06-25',
                'resultado' => 'Prestamo creado y libro cambia a PRESTADO',
                'estado' => 'PASSED',
            ],
            [
                'id' => 'CP10',
                'historia' => 'HU02 - Gestion de Prestamos y Exclusividad',
                'modulo' => 'Prestamos',
                'caso' => 'Libro prestado no puede volver a prestarse',
                'tipo' => 'Integracion / Control de estado',
                'categoria' => 'integracion',
                'entrada' => 'Usuario estudiante, libro PRESTADO, fecha 2026-06-25',
                'resultado' => 'Prestamo rechazado y no se crea nuevo registro',
                'estado' => 'PASSED',
            ],
            [
                'id' => 'CP11',
                'historia' => 'HU03 - Morosidad, Pago y Penalizacion',
                'modulo' => 'Morosidad',
                'caso' => 'Docente con 10 dias de retraso genera multa S/ 50.00',
                'tipo' => 'Unitaria / Regla de negocio',
                'categoria' => 'unitaria',
                'entrada' => 'Rol docente, devolucion 2026-06-15, actual 2026-06-25',
                'resultado' => '10 dias, tarifa S/ 5.00, multa S/ 50.00, MOROSO',
                'estado' => 'PASSED',
            ],
            [
                'id' => 'CP12',
                'historia' => 'HU03 - Morosidad, Pago y Penalizacion',
                'modulo' => 'Morosidad',
                'caso' => 'Estudiante con 10 dias de retraso genera multa S/ 20.00',
                'tipo' => 'Unitaria / Regla de negocio',
                'categoria' => 'unitaria',
                'entrada' => 'Rol estudiante, devolucion 2026-06-15, actual 2026-06-25',
                'resultado' => '10 dias, tarifa S/ 2.00, multa S/ 20.00, MOROSO',
                'estado' => 'PASSED',
            ],
            [
                'id' => 'CP13',
                'historia' => 'HU03 - Morosidad, Pago y Penalizacion',
                'modulo' => 'Morosidad',
                'caso' => 'Usuario sin retraso queda AL_DIA y multa 0.00',
                'tipo' => 'Unitaria / Caja negra',
                'categoria' => 'unitaria',
                'entrada' => 'Rol estudiante, devolucion 2026-06-25, actual 2026-06-25',
                'resultado' => '0 dias, multa S/ 0.00, AL_DIA',
                'estado' => 'PASSED',
            ],
            [
                'id' => 'CP14',
                'historia' => 'HU03 - Morosidad, Pago y Penalizacion',
                'modulo' => 'Morosidad',
                'caso' => 'Rol invalido no calcula morosidad',
                'tipo' => 'Unitaria / Caja negra',
                'categoria' => 'unitaria',
                'entrada' => 'Rol invitado, devolucion 2026-06-15, actual 2026-06-25',
                'resultado' => 'Calculo rechazado, estado ERROR',
                'estado' => 'PASSED',
            ],
            [
                'id' => 'CP15',
                'historia' => 'HU03 - Morosidad, Pago y Penalizacion',
                'modulo' => 'Morosidad / Pago',
                'caso' => 'Pago de multa detiene acumulacion de morosidad',
                'tipo' => 'Unitaria / Regresion futura',
                'categoria' => 'unitaria',
                'entrada' => 'Docente, devolucion 2026-06-15, pago 2026-06-25, actual 2026-06-30',
                'resultado' => 'Multa congelada en S/ 50.00, estado PAGADA',
                'estado' => 'PASSED',
            ],
            [
                'id' => 'CP16',
                'historia' => 'HU03 - Morosidad, Pago y Penalizacion',
                'modulo' => 'Penalizacion',
                'caso' => 'Despues del pago inicia penalizacion de 21 dias',
                'tipo' => 'Unitaria / Dominio',
                'categoria' => 'unitaria',
                'entrada' => 'Pago 2026-06-25, actual 2026-06-30',
                'resultado' => 'Habilitacion 2026-07-16, 16 dias restantes, PENALIZADO',
                'estado' => 'PASSED',
            ],
            [
                'id' => 'CP17',
                'historia' => 'HU03 - Morosidad, Pago y Penalizacion',
                'modulo' => 'Penalizacion',
                'caso' => 'Usuario queda habilitado cuando termina penalizacion',
                'tipo' => 'Unitaria / Dominio',
                'categoria' => 'unitaria',
                'entrada' => 'Pago 2026-06-25, actual 2026-07-16',
                'resultado' => '0 dias restantes, puede prestar, HABILITADO',
                'estado' => 'PASSED',
            ],
            [
                'id' => 'CP18',
                'historia' => 'HU03 - Morosidad, Pago y Penalizacion',
                'modulo' => 'Morosidad / Pagos',
                'caso' => 'Pago registra fecha, congela deuda e inicia penalizacion',
                'tipo' => 'Integracion / Persistencia',
                'categoria' => 'integracion',
                'entrada' => 'Docente moroso, prestamo VENCIDO, pago 2026-06-25',
                'resultado' => 'Pago creado, multa S/ 50.00, habilitacion 2026-07-16, PENALIZADO',
                'estado' => 'PASSED',
            ],
            [
                'id' => 'CP19',
                'historia' => 'HU03 - Morosidad, Pago y Penalizacion',
                'modulo' => 'Morosidad + Prestamos',
                'caso' => 'Usuario penalizado no puede registrar nuevo prestamo',
                'tipo' => 'Integracion / Sistema',
                'categoria' => 'integracion',
                'entrada' => 'Usuario PENALIZADO, habilitacion 2026-07-16, prestamo 2026-06-30',
                'resultado' => 'Prestamo rechazado, libro permanece DISPONIBLE',
                'estado' => 'PASSED',
            ],
            [
                'id' => 'CP20',
                'historia' => 'HU03 - Morosidad, Pago y Penalizacion',
                'modulo' => 'Morosidad + Prestamos',
                'caso' => 'Usuario habilitado si puede registrar prestamo',
                'tipo' => 'Integracion / Sistema',
                'categoria' => 'integracion',
                'entrada' => 'Usuario con habilitacion 2026-07-16, prestamo 2026-07-16',
                'resultado' => 'Prestamo aceptado, libro PRESTADO, devolucion 2026-07-30',
                'estado' => 'PASSED',
            ],
            [
                'id' => 'CP21',
                'historia' => 'Smoke Test final',
                'modulo' => 'Sistema',
                'caso' => 'Smoke Test final del sistema BiblioTech',
                'tipo' => 'Humo / Regresion basica',
                'categoria' => 'humo',
                'entrada' => 'Servicios, modelos, tablas y entorno de testing',
                'resultado' => 'Componentes principales disponibles',
                'estado' => 'PASSED',
            ],
        ];

        return view('pruebas.index', [
            'casosPorHistoria' => collect($casos)->groupBy('historia'),
            'resumen' => [
                'total' => count($casos),
                'unitarias' => collect($casos)->where('categoria', 'unitaria')->count(),
                'integracion' => collect($casos)->where('categoria', 'integracion')->count(),
                'humo' => collect($casos)->where('categoria', 'humo')->count(),
                'estado' => 'PASSED',
            ],
        ]);
    }
}
